In [1]:
import requests
import pandas as pd
import json
import time
import os

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
#Set API Base URL

BASE_URL = "http://127.0.0.1:8000"

print("API Base URL:", BASE_URL)

API Base URL: http://127.0.0.1:8000

In [3]:
#Check API Health

response = requests.get(f"{BASE_URL}/")

print("Status Code:", response.status_code)
print(json.dumps(response.json(), indent=4))

Status Code: 200
{
    "message": "Student Memory Personalization API is running.",
    "component": "Component 3: Memory (Student Personalization)",
    "memory_layers": [
        "short-term memory",
        "long-term memory",
        "concept-based memory"
    ]
}

In [4]:
#Test Case 1: Add First Wrong Interaction; This tests whether memory is created for a new student.

#Send First Interaction

student_id = 999001
session_id = 5001
concept_name = "Percent Of"

interaction_1 = {
    "student_id": student_id,
    "session_id": session_id,
    "problem_id": 101,
    "concept_name": concept_name,
    "correct": 0,
    "attempt_count": 2,
    "hint_count": 1,
    "hint_total": 3,
    "response_time_ms": 45000
}

response = requests.post(
    f"{BASE_URL}/memory/update",
    json=interaction_1
)

print("Status Code:", response.status_code)
result_1 = response.json()
print(json.dumps(result_1, indent=4))

Status Code: 200
{
    "message": "Memory updated successfully.",
    "student_id": 999001,
    "target_concept": "Percent Of",
    "short_term_memory": {
        "student_id": 999001,
        "session_id": 5001,
        "current_concept": "Percent Of",
        "recent_interaction_count": 3,
        "recent_accuracy": 0.33,
        "average_attempts": 1.67,
        "recent_hint_usage": 2,
        "session_status": "needs_support",
        "updated_at": "2026-05-06 11:59:33"
    },
    "long_term_memory": {
        "student_id": 999001,
        "total_interactions": 3,
        "total_sessions": 1,
        "total_concepts": 1,
        "overall_accuracy": 0.33,
        "average_attempts": 1.67,
        "average_hint_count": 0.67,
        "total_hint_count": 2,
        "average_response_time_ms": 40000.0,
        "preferred_support_style": "basic_explanation_support",
        "updated_at": "2026-05-06 11:59:33"
    },
    "concept_based_memory": {
        "student_id": 999001,
        "concept_name": "Percent Of",
        "total_interactions": 3,
        "correct_count": 1,
        "wrong_count": 2,
        "accuracy": 0.33,
        "total_hints": 2,
        "avg_hints": 0.67,
        "avg_attempts": 1.67,
        "avg_response_time_ms": 40000.0,
        "updated_at": "2026-05-06 11:59:33"
    },
    "integration_note": {
        "for_meta_agent": "Use this stored interaction history to derive mastery, knowledge graph updates, regression flags, and learning paths.",
        "for_fapr_lb": "Use this memory context as input features for struggle prediction and repair strategy selection.",
        "for_tutor_agent": "Use this context to personalize explanations without treating the student as new."
    }
}

In [5]:
#Convert First Result to Test Summary

test_1 = {
    "test_case": "First wrong interaction",
    "expected_recent_interaction_count": 1,
    "actual_recent_interaction_count": result_1["short_term_memory"].get("recent_interaction_count"),
    "expected_recent_accuracy": 0.0,
    "actual_recent_accuracy": result_1["short_term_memory"].get("recent_accuracy"),
    "expected_correct_count": 0,
    "actual_correct_count": result_1["concept_based_memory"].get("correct_count"),
    "expected_wrong_count": 1,
    "actual_wrong_count": result_1["concept_based_memory"].get("wrong_count"),
    "status": "PASS" if (
        result_1["short_term_memory"].get("recent_interaction_count") == 1 and
        result_1["short_term_memory"].get("recent_accuracy") == 0.0 and
        result_1["concept_based_memory"].get("correct_count") == 0 and
        result_1["concept_based_memory"].get("wrong_count") == 1
    ) else "FAIL"
}

test_1

{'test_case': 'First wrong interaction',
 'expected_recent_interaction_count': 1,
 'actual_recent_interaction_count': 3,
 'expected_recent_accuracy': 0.0,
 'actual_recent_accuracy': 0.33,
 'expected_correct_count': 0,
 'actual_correct_count': 1,
 'expected_wrong_count': 1,
 'actual_wrong_count': 2,
 'status': 'FAIL'}

In [6]:
#Test Case 2: Add Second Correct Interaction; This tests whether memory updates after another interaction.

#Send Second Interaction

interaction_2 = {
    "student_id": student_id,
    "session_id": session_id,
    "problem_id": 102,
    "concept_name": concept_name,
    "correct": 1,
    "attempt_count": 1,
    "hint_count": 0,
    "hint_total": 3,
    "response_time_ms": 30000
}

response = requests.post(
    f"{BASE_URL}/memory/update",
    json=interaction_2
)

print("Status Code:", response.status_code)
result_2 = response.json()
print(json.dumps(result_2, indent=4))

Status Code: 200
{
    "message": "Memory updated successfully.",
    "student_id": 999001,
    "target_concept": "Percent Of",
    "short_term_memory": {
        "student_id": 999001,
        "session_id": 5001,
        "current_concept": "Percent Of",
        "recent_interaction_count": 4,
        "recent_accuracy": 0.5,
        "average_attempts": 1.5,
        "recent_hint_usage": 2,
        "session_status": "moderate_progress",
        "updated_at": "2026-05-06 12:01:35"
    },
    "long_term_memory": {
        "student_id": 999001,
        "total_interactions": 4,
        "total_sessions": 1,
        "total_concepts": 1,
        "overall_accuracy": 0.5,
        "average_attempts": 1.5,
        "average_hint_count": 0.5,
        "total_hint_count": 2,
        "average_response_time_ms": 37500.0,
        "preferred_support_style": "basic_explanation_support",
        "updated_at": "2026-05-06 12:01:35"
    },
    "concept_based_memory": {
        "student_id": 999001,
        "concept_name": "Percent Of",
        "total_interactions": 4,
        "correct_count": 2,
        "wrong_count": 2,
        "accuracy": 0.5,
        "total_hints": 2,
        "avg_hints": 0.5,
        "avg_attempts": 1.5,
        "avg_response_time_ms": 37500.0,
        "updated_at": "2026-05-06 12:01:35"
    },
    "integration_note": {
        "for_meta_agent": "Use this stored interaction history to derive mastery, knowledge graph updates, regression flags, and learning paths.",
        "for_fapr_lb": "Use this memory context as input features for struggle prediction and repair strategy selection.",
        "for_tutor_agent": "Use this context to personalize explanations without treating the student as new."
    }
}

In [7]:
#Test Second Result

test_2 = {
    "test_case": "Second correct interaction",
    "expected_recent_interaction_count": 2,
    "actual_recent_interaction_count": result_2["short_term_memory"].get("recent_interaction_count"),
    "expected_recent_accuracy": 0.5,
    "actual_recent_accuracy": result_2["short_term_memory"].get("recent_accuracy"),
    "expected_correct_count": 1,
    "actual_correct_count": result_2["concept_based_memory"].get("correct_count"),
    "expected_wrong_count": 1,
    "actual_wrong_count": result_2["concept_based_memory"].get("wrong_count"),
    "status": "PASS" if (
        result_2["short_term_memory"].get("recent_interaction_count") == 2 and
        result_2["short_term_memory"].get("recent_accuracy") == 0.5 and
        result_2["concept_based_memory"].get("correct_count") == 1 and
        result_2["concept_based_memory"].get("wrong_count") == 1
    ) else "FAIL"
}

test_2

{'test_case': 'Second correct interaction',
 'expected_recent_interaction_count': 2,
 'actual_recent_interaction_count': 4,
 'expected_recent_accuracy': 0.5,
 'actual_recent_accuracy': 0.5,
 'expected_correct_count': 1,
 'actual_correct_count': 2,
 'expected_wrong_count': 1,
 'actual_wrong_count': 2,
 'status': 'FAIL'}

In [8]:
#Test Case 3: Add Third Correct Interaction; This tests whether session status changes after performance improves.

#Send Third Interaction

interaction_3 = {
    "student_id": student_id,
    "session_id": session_id,
    "problem_id": 103,
    "concept_name": concept_name,
    "correct": 1,
    "attempt_count": 1,
    "hint_count": 0,
    "hint_total": 3,
    "response_time_ms": 25000
}

response = requests.post(
    f"{BASE_URL}/memory/update",
    json=interaction_3
)

print("Status Code:", response.status_code)
result_3 = response.json()
print(json.dumps(result_3, indent=4))

Status Code: 200
{
    "message": "Memory updated successfully.",
    "student_id": 999001,
    "target_concept": "Percent Of",
    "short_term_memory": {
        "student_id": 999001,
        "session_id": 5001,
        "current_concept": "Percent Of",
        "recent_interaction_count": 5,
        "recent_accuracy": 0.6,
        "average_attempts": 1.4,
        "recent_hint_usage": 2,
        "session_status": "moderate_progress",
        "updated_at": "2026-05-06 12:04:53"
    },
    "long_term_memory": {
        "student_id": 999001,
        "total_interactions": 5,
        "total_sessions": 1,
        "total_concepts": 1,
        "overall_accuracy": 0.6,
        "average_attempts": 1.4,
        "average_hint_count": 0.4,
        "total_hint_count": 2,
        "average_response_time_ms": 35000.0,
        "preferred_support_style": "basic_explanation_support",
        "updated_at": "2026-05-06 12:04:53"
    },
    "concept_based_memory": {
        "student_id": 999001,
        "concept_name": "Percent Of",
        "total_interactions": 5,
        "correct_count": 3,
        "wrong_count": 2,
        "accuracy": 0.6,
        "total_hints": 2,
        "avg_hints": 0.4,
        "avg_attempts": 1.4,
        "avg_response_time_ms": 35000.0,
        "updated_at": "2026-05-06 12:04:53"
    },
    "integration_note": {
        "for_meta_agent": "Use this stored interaction history to derive mastery, knowledge graph updates, regression flags, and learning paths.",
        "for_fapr_lb": "Use this memory context as input features for struggle prediction and repair strategy selection.",
        "for_tutor_agent": "Use this context to personalize explanations without treating the student as new."
    }
}

In [9]:
#Test Third Result

test_3 = {
    "test_case": "Third correct interaction",
    "expected_recent_interaction_count": 3,
    "actual_recent_interaction_count": result_3["short_term_memory"].get("recent_interaction_count"),
    "expected_correct_count": 2,
    "actual_correct_count": result_3["concept_based_memory"].get("correct_count"),
    "expected_wrong_count": 1,
    "actual_wrong_count": result_3["concept_based_memory"].get("wrong_count"),
    "expected_session_status": "moderate_progress",
    "actual_session_status": result_3["short_term_memory"].get("session_status"),
    "status": "PASS" if (
        result_3["short_term_memory"].get("recent_interaction_count") == 3 and
        result_3["concept_based_memory"].get("correct_count") == 2 and
        result_3["concept_based_memory"].get("wrong_count") == 1 and
        result_3["short_term_memory"].get("session_status") == "moderate_progress"
    ) else "FAIL"
}

test_3

{'test_case': 'Third correct interaction',
 'expected_recent_interaction_count': 3,
 'actual_recent_interaction_count': 5,
 'expected_correct_count': 2,
 'actual_correct_count': 3,
 'expected_wrong_count': 1,
 'actual_wrong_count': 2,
 'expected_session_status': 'moderate_progress',
 'actual_session_status': 'moderate_progress',
 'status': 'FAIL'}

In [10]:
#Test Case 4: Add New Concept for Same Student; This tests whether concept-based memory separates concepts correctly.

#Send New Concept Interaction

interaction_4 = {
    "student_id": student_id,
    "session_id": session_id,
    "problem_id": 201,
    "concept_name": "Circle Graph",
    "correct": 0,
    "attempt_count": 3,
    "hint_count": 2,
    "hint_total": 4,
    "response_time_ms": 60000
}

response = requests.post(
    f"{BASE_URL}/memory/update",
    json=interaction_4
)

print("Status Code:", response.status_code)
result_4 = response.json()
print(json.dumps(result_4, indent=4))

Status Code: 200
{
    "message": "Memory updated successfully.",
    "student_id": 999001,
    "target_concept": "Circle Graph",
    "short_term_memory": {
        "student_id": 999001,
        "session_id": 5001,
        "current_concept": "Circle Graph",
        "recent_interaction_count": 6,
        "recent_accuracy": 0.5,
        "average_attempts": 1.67,
        "recent_hint_usage": 4,
        "session_status": "moderate_progress",
        "updated_at": "2026-05-06 12:07:29"
    },
    "long_term_memory": {
        "student_id": 999001,
        "total_interactions": 6,
        "total_sessions": 1,
        "total_concepts": 2,
        "overall_accuracy": 0.5,
        "average_attempts": 1.67,
        "average_hint_count": 0.67,
        "total_hint_count": 4,
        "average_response_time_ms": 39166.67,
        "preferred_support_style": "basic_explanation_support",
        "updated_at": "2026-05-06 12:07:29"
    },
    "concept_based_memory": {
        "student_id": 999001,
        "concept_name": "Circle Graph",
        "total_interactions": 1,
        "correct_count": 0,
        "wrong_count": 1,
        "accuracy": 0.0,
        "total_hints": 2,
        "avg_hints": 2.0,
        "avg_attempts": 3.0,
        "avg_response_time_ms": 60000.0,
        "updated_at": "2026-05-06 12:07:29"
    },
    "integration_note": {
        "for_meta_agent": "Use this stored interaction history to derive mastery, knowledge graph updates, regression flags, and learning paths.",
        "for_fapr_lb": "Use this memory context as input features for struggle prediction and repair strategy selection.",
        "for_tutor_agent": "Use this context to personalize explanations without treating the student as new."
    }
}

In [11]:
#Test New Concept Result

test_4 = {
    "test_case": "New concept interaction",
    "expected_target_concept": "Circle Graph",
    "actual_target_concept": result_4.get("target_concept"),
    "expected_total_concepts": 2,
    "actual_total_concepts": result_4["long_term_memory"].get("total_concepts"),
    "expected_circle_graph_interactions": 1,
    "actual_circle_graph_interactions": result_4["concept_based_memory"].get("total_interactions"),
    "status": "PASS" if (
        result_4.get("target_concept") == "Circle Graph" and
        result_4["long_term_memory"].get("total_concepts") == 2 and
        result_4["concept_based_memory"].get("total_interactions") == 1
    ) else "FAIL"
}

test_4

{'test_case': 'New concept interaction',
 'expected_target_concept': 'Circle Graph',
 'actual_target_concept': 'Circle Graph',
 'expected_total_concepts': 2,
 'actual_total_concepts': 2,
 'expected_circle_graph_interactions': 1,
 'actual_circle_graph_interactions': 1,
 'status': 'PASS'}

In [12]:
#Test Case 5: Retrieve Updated Memory Context; Now check whether the retrieval endpoint returns the updated student memory.

#Retrieve Memory Context

response = requests.get(f"{BASE_URL}/memory/context/{student_id}")

print("Status Code:", response.status_code)
retrieved_context = response.json()
print(json.dumps(retrieved_context, indent=4))

Status Code: 200
{
    "found": false,
    "message": "Student not found in short-term memory.",
    "student_id": 999001
}

In [13]:
#Test Retrieval

test_5 = {
    "test_case": "Retrieve updated memory context",
    "expected_student_id": student_id,
    "actual_student_id": retrieved_context.get("student_id"),
    "has_short_term_memory": "short_term_memory" in retrieved_context,
    "has_long_term_memory": "long_term_memory" in retrieved_context,
    "has_concept_based_memory": "concept_based_memory" in retrieved_context,
    "status": "PASS" if (
        retrieved_context.get("student_id") == student_id and
        "short_term_memory" in retrieved_context and
        "long_term_memory" in retrieved_context and
        "concept_based_memory" in retrieved_context
    ) else "FAIL"
}

test_5

{'test_case': 'Retrieve updated memory context',
 'expected_student_id': 999001,
 'actual_student_id': 999001,
 'has_short_term_memory': False,
 'has_long_term_memory': False,
 'has_concept_based_memory': False,
 'status': 'FAIL'}

In [14]:
#Step 5: Create Final Test Results Table

#Combine All Test Results

test_results = pd.DataFrame([
    test_1,
    test_2,
    test_3,
    test_4,
    test_5
])

test_results

,test_case,expected_recent_interaction_count,actual_recent_interaction_count,expected_recent_accuracy,actual_recent_accuracy,expected_correct_count,actual_correct_count,expected_wrong_count,actual_wrong_count,status,...,actual_target_concept,expected_total_concepts,actual_total_concepts,expected_circle_graph_interactions,actual_circle_graph_interactions,expected_student_id,actual_student_id,has_short_term_memory,has_long_term_memory,has_concept_based_memory
0,First wrong interaction,1.0,3.0,0.0,0.33,0.0,1.0,1.0,2.0,FAIL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Second correct interaction,2.0,4.0,0.5,0.50,1.0,2.0,1.0,2.0,FAIL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Third correct interaction,3.0,5.0,NaN,NaN,2.0,3.0,1.0,2.0,FAIL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,New concept interaction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PASS,...,Circle Graph,2.0,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
4,Retrieve updated memory context,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FAIL,...,NaN,NaN,NaN,NaN,NaN,999001.0,999001.0,False,False,False

In [15]:
#Count Passed and Failed Tests

summary = test_results["status"].value_counts().reset_index()
summary.columns = ["status", "count"]

summary

  status  count
0   FAIL      4
1   PASS      1

In [16]:
#Step 6: Save Test Outputs

#Save Results

os.makedirs("../outputs/tables", exist_ok=True)
os.makedirs("../outputs/api_results", exist_ok=True)

test_results.to_csv(
    "../outputs/tables/dynamic_memory_api_test_results.csv",
    index=False
)

summary.to_csv(
    "../outputs/tables/dynamic_memory_api_test_summary.csv",
    index=False
)

with open("../outputs/api_results/final_dynamic_memory_context.json", "w") as f:
    json.dump(retrieved_context, f, indent=4, default=str)

print("Dynamic memory API test outputs saved successfully.")

Dynamic memory API test outputs saved successfully.